name: textfield_search
description: A new Flutter package which uses a TextField to search and select it's value from a simple list.
homepage: https://github.com/alexrindone/flutter_textfield_search
version: 0.2.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
